# steps:
# - name: gcr.io/cloud-builders/docker
#   args:
#     - "build"
#     - "--build-arg"
#     - "MASTER_KEY=97cf4e88cd9a85e791ca14dd373eaa272df1eb2be5b580b134606f4a61bba86b633663ae2c76ed003643368496ef979298e52efe044a98231e74f98b90de1dd6"
#     - "-t"
#     - "us.gcr.io/$PROJECT_ID/workspace_ruby:latest"
#     - "-f"
#     - "./Dockerfile"
#     - "./"

# images:
# - us.gcr.io/$PROJECT_ID/workspace_ruby:latest


# [START cloudrun_rails_cloudbuild]
steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args: ["-c", "docker build --build-arg MASTER_KEY=97cf4e88cd9a85e791ca14dd373eaa272df1eb2be5b580b134606f4a61bba86b633663ae2c76ed003643368496ef979298e52efe044a98231e74f98b90de1dd6 -t gcr.io/${PROJECT_ID}/${_SERVICE_NAME} . "]
    secretEnv: ["RAILS_KEY"]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]


images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"
# [END cloudrun_rails_cloudbuild]